apiVersion: v1
kind: Service
metadata:
  name: {{ include "jobberwocky.fullname" . }}
  labels:
    app: {{ include "jobberwocky.name" . }}
spec:
  selector:
    app: {{ include "jobberwocky.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}
